
'use strict';var menuArrows=document.querySelectorAll('.menu__arrow');if(menuArrows.length>0){var _loop=function _loop(i){var menuArrow=menuArrows[i];menuArrow.addEventListener('click',function(e){menuArrow.parentElement.classList.toggle('_active');});};for(var i=0;i<menuArrows.length;i++){_loop(i);}}
var burger=document.querySelector('.header__burger');var menu=document.querySelector('.menu__body');burger.addEventListener('click',function(){burger.classList.toggle('_active');menu.classList.toggle('_active');document.body.classList.toggle('_lock');});var lastScroll=0;var defaultOffset=100;var header=document.querySelector('.header');var scrollTopButton=document.querySelector('.scroll-top__button');var scrollPosition=function scrollPosition(){return window.pageYOffset||document.documentElement.scrollTop;};var containHide=function containHide(){return header.classList.contains('_hide');};window.addEventListener('scroll',function(){if(scrollPosition()>lastScroll&&!containHide()&&scrollPosition()>defaultOffset){header.classList.add('_hide');}else if(scrollPosition()<lastScroll&&containHide()){header.classList.remove('_hide');}
if(lastScroll>100){header.classList.add('_paint');}else{header.classList.remove('_paint');}
if(lastScroll>600){scrollTopButton.classList.add('_show');}else{scrollTopButton.classList.remove('_show');}
lastScroll=scrollPosition();});var forms=document.querySelectorAll('.validation-form');if(forms){var _loop2=function _loop2(i){var form=forms[i];form.addEventListener('submit',function(e){var name=form.querySelector('.validation-name');var phone=form.querySelector('.validation-phone');var checkbox=form.querySelector('.validation-checkbox');var formAlert=form.querySelector('.validation-alert');var formLabel=form.querySelector('.validation-label');if(name.value==''||name.value==null){e.preventDefault();formAlert.classList.add('_error');name.classList.add('_error');}else{name.classList.remove('_error');}
if(phone.value==''||phone.value==null){e.preventDefault();formAlert.classList.add('_error');phone.classList.add('_error');}else{phone.classList.remove('_error');}
if(!checkbox.checked){e.preventDefault();formAlert.classList.add('_error');formLabel.classList.add('_error');}else{formLabel.classList.remove('_error');}});};for(var i=0;i<forms.length;i++){_loop2(i);}}
document.addEventListener('DOMContentLoaded',function(){document.getElementById('scroll-top-btn').onclick=function(){scrollTo(0,500);};});function scrollTo(to){var duration=arguments.length>1&&arguments[1]!==undefined?arguments[1]:0;var element=document.scrollingElement||document.documentElement,start=element.scrollTop,change=to-start,startDate=+new Date(),easeInOutQuad=function easeInOutQuad(t,b,c,d){t/=d/2;if(t<1)return c/2*t*t+b;t--;return-c/2*(t*(t-2)-1)+b;},animateScroll=function animateScroll(){var currentDate=+new Date();var currentTime=currentDate-startDate;element.scrollTop=parseInt(easeInOutQuad(currentTime,start,change,duration));if(currentTime<duration){requestAnimationFrame(animateScroll);}else{element.scrollTop=to;}};animateScroll();}"use strict";window.onload=function(){var parallax=document.querySelector('.mainscreen');var short=document.querySelector('.short');if(document.body.clientWidth>992){if(parallax){var setMouseParallaxStyle=function setMouseParallaxStyle(){var distX=coordXPercent-positionX;var distY=coordYPercent-positionY;positionX+=distX*speed;positionY+=distY*speed;letter.style.cssText='transform: translate('+positionX/ratio+'%,'+positionY/ratio+'%);';requestAnimationFrame(setMouseParallaxStyle);};var letter=document.querySelector('.mainscreen__decor');var ratio=50;var speed=0.02;var positionX=0;var positionY=0;var coordXPercent=0;var coordYPercent=0;setMouseParallaxStyle();parallax.addEventListener('mousemove',function(e){var parallaxWidth=letter.offsetWidth;var parallaxHeight=letter.offsetHeight;var coordX=e.pageX-parallaxWidth/2;var coordY=e.pageY-parallaxHeight/2;coordXPercent=coordX/parallaxWidth*100;coordYPercent=coordY/parallaxHeight*100;});}
if(short){var setParallaxItemsStyle=function setParallaxItemsStyle(scrollTopPercent){watermark.style.cssText='transform: translate(0%,-'+scrollTopPercent/3+'%);';};var watermark=document.querySelector('.short__watermark');var thresholdSets=[];for(var i=0;i<=1.0;i+=0.01){thresholdSets.push(i);}
var callback=function callback(entries,observer){var scrollTopPercent=window.pageYOffset/short.offsetHeight*100;setParallaxItemsStyle(scrollTopPercent);};var observer=new IntersectionObserver(callback,{threshold:thresholdSets});observer.observe(short);}}};document.querySelectorAll('.tabs__trigger').forEach(function(trigger){trigger.addEventListener('click',function(e){e.preventDefault();var id=e.target.getAttribute('href').replace('#','');var tabTitle=e.target.innerText;var pageTitle=document.querySelector('.bar__subtitle');pageTitle.innerText=tabTitle;document.querySelectorAll('.tabs__trigger').forEach(function(child){return child.classList.remove('tabs__trigger--active');});document.querySelectorAll('.tabs__item').forEach(function(child){return child.classList.remove('tabs__item--active');});trigger.classList.add('tabs__trigger--active');document.getElementById(id).classList.add('tabs__item--active');});});if(document.querySelector('.tabs__trigger')){document.querySelector('.tabs__trigger').click();}
var filterBtns=document.querySelectorAll('.filter__check-btn');if(filterBtns){var _loop3=function _loop3(i){var filterBtn=filterBtns[i];filterBtn.addEventListener('click',function(){filterBtn.classList.toggle('filter__check-btn--active');});};for(var i=0;i<filterBtns.length;i++){_loop3(i);}}
if(document.querySelector('.slider')){new Swiper('.slider',{navigation:{nextEl:'.swiper-button-next',prevEl:'.swiper-button-prev'},autoHeight:true,slideToClickedSlide:true,watchOverflow:true,observer:true,observeParents:true,observeSlideChildren:true,preloadImages:false,lazy:{loadOnTransitionStart:false,loadPrevNext:false},watchSlidesProgress:true,watchSlidesVisibility:true,thumbs:{swiper:{el:'.slider-small',watchOverflow:true,observer:true,observeParents:true,observeSlideChildren:true,spaceBetween:15,slideToClickedSlide:true,preloadImages:false,lazy:{loadOnTransitionStart:false,loadPrevNext:false},watchSlidesProgress:true,watchSlidesVisibility:true,breakpoints:{320:{slidesPerView:3},501:{slidesPerView:5}}}}});}
var rent=document.querySelector('.rent');if(rent){var init=function init(){var map=new ymaps.Map('map-objects',{center:center,zoom:16});var map1=new ymaps.Map('map-commercial',{center:center,zoom:16});var placemarks=[];var placemarks1=[];map.controls.remove('searchControl');map.controls.remove('trafficControl');map.controls.remove('geolocationControl');map.controls.remove('typeSelector');map.controls.remove('fullscreenControl');map.controls.remove('rulerControl');map.controls.remove(['scrollZoom']);map.behaviors.disable('scrollZoom');map1.controls.remove('searchControl');map1.controls.remove('trafficControl');map1.controls.remove('geolocationControl');map1.controls.remove('typeSelector');map1.controls.remove('fullscreenControl');map1.controls.remove('rulerControl');map1.controls.remove(['scrollZoom']);map1.behaviors.disable('scrollZoom');var mapObjects=document.getElementById('map-objects');var mapCommercial=document.getElementById('map-commercial');var mapLinks=mapObjects.querySelectorAll('.map__link');var mapLinksCommercial=mapCommercial.querySelectorAll('.map__link');var _loop4=function _loop4(i){var mapLink=mapLinks[i];var title=mapLink.querySelector('.map__heading').innerText;var address=mapLink.querySelector('.map__address').innerText;placemarks[i]=new ymaps.Placemark([Number(mapLink.dataset.latitude),Number(mapLink.dataset.longitude)],{balloonContentHeader:'\n\t\t\t\t<a href="#" class="balloon-title">'+address+'</a>\n\t\t\t\t',balloonContentFooter:''+title},{iconLayout:'default#image',iconImageHref:'template/images/placemark.svg',iconImageSize:[150,150],iconImageOffset:[-70,-85]});map.geoObjects.add(placemarks[i]);mapLink.addEventListener('mouseenter',function(){map.panTo([Number(mapLink.dataset.latitude),Number(mapLink.dataset.longitude)],{duration:700});map.balloon.open([Number(mapLink.dataset.latitude),Number(mapLink.dataset.longitude)],{content:'\n\t\t\t\t\t<div class="balloon-wrapper">\n\t\t\t\t\t\t<div class="balloon-title-wrap">\n\t\t\t\t\t\t\t<a href="#" class="balloon-title">'+address+'</a>\n\t\t\t\t\t\t</div>\n\t\t\t\t\t\t<div class="balloon-footer">\n\t\t\t\t\t\t\t'+title+'\n\t\t\t\t\t\t</div>\n\t\t\t\t\t</div>\n\t\t\t\t'});});};for(var i=0;i<mapLinks.length;i++){_loop4(i);}
var _loop5=function _loop5(i){var mapLinkCommercial=mapLinksCommercial[i];var title=mapLinkCommercial.querySelector('.map__heading').innerText;var address=mapLinkCommercial.querySelector('.map__address').innerText;placemarks1[i]=new ymaps.Placemark([Number(mapLinkCommercial.dataset.latitude),Number(mapLinkCommercial.dataset.longitude)],{balloonContentHeader:'\n\t\t\t\t<a href="#" class="balloon-title">'+address+'</a>\n\t\t\t\t',balloonContentFooter:''+title},{iconLayout:'default#image',iconImageHref:'template/images/placemark.svg',iconImageSize:[150,150],iconImageOffset:[-70,-85]});map1.geoObjects.add(placemarks1[i]);mapLinkCommercial.addEventListener('mouseenter',function(){map1.panTo([Number(mapLinkCommercial.dataset.latitude),Number(mapLinkCommercial.dataset.longitude)],{duration:700});map1.balloon.open([Number(mapLinkCommercial.dataset.latitude),Number(mapLinkCommercial.dataset.longitude)],{content:'\n\t\t\t\t\t<div class="balloon-wrapper">\n\t\t\t\t\t\t<div class="balloon-title-wrap">\n\t\t\t\t\t\t\t<a href="#" class="balloon-title">'+address+'</a>\n\t\t\t\t\t\t</div>\n\t\t\t\t\t\t<div class="balloon-footer">\n\t\t\t\t\t\t\t'+title+'\n\t\t\t\t\t\t</div>\n\t\t\t\t\t</div>\n\t\t\t\t'});});};for(var i=0;i<mapLinksCommercial.length;i++){_loop5(i);}};ymaps.ready(init);var center=[55.159608119492844,61.40261080259067];}
if(document.querySelector('.swiper')){new Swiper('.swiper',{navigation:{nextEl:'.swiper__button-next',prevEl:'.swiper__button-prev'},keyboard:{enabled:true,onlyInViewport:true},slidesPerView:3,watchOverflow:true,spaceBetween:30,breakpoints:{320:{slidesPerView:1,spaceBetween:10},360:{slidesPerView:1.5},480:{slidesPerView:2},992:{slidesPerView:2.5,spaceBetween:20},1024:{slidesPerView:3,spaceBetween:30}}});}
$(document).ready(function(){$('.partners__slider').slick({arrows:false,slidesToShow:4,rows:3,autoplay:true,pauseOnHover:false,responsive:[{breakpoint:1280,settings:{slidesToShow:3}},{breakpoint:993,settings:{slidesToShow:2}},{breakpoint:600,settings:{slidesToShow:1}}]});});'use strict';var popupLinks=document.querySelectorAll('.popup-link');var body=document.querySelector('body');var lockPadding=document.querySelectorAll('.lock-padding');var unlock=true;var timeout=500;if(popupLinks.length>0){var _loop=function _loop(index){var popupLink=popupLinks[index];popupLink.addEventListener("click",function(e){var popupName=popupLink.getAttribute('href').replace('#','');var currentPopup=document.getElementById(popupName);popupOpen(currentPopup);e.preventDefault();});};for(var index=0;index<popupLinks.length;index++){_loop(index);}}
var popupCloseIcon=document.querySelectorAll('.close-popup');if(popupCloseIcon.length>0){var _loop2=function _loop2(index){var el=popupCloseIcon[index];el.addEventListener('click',function(e){if(burger.classList.contains('_active')){burger.classList.remove('_active');menu.classList.remove('_active');document.body.classList.remove('_lock');}
popupClose(el.closest('.popup'));e.preventDefault();});};for(var index=0;index<popupCloseIcon.length;index++){_loop2(index);}}
function popupOpen(currentPopup){if(currentPopup&&unlock){var popupActive=document.querySelector('.popup._open');if(popupActive){popupClose(popupActive,false);}else{bodyLock();}
currentPopup.classList.add('_open');currentPopup.addEventListener('click',function(e){if(!e.target.closest('.popup__content')){popupClose(e.target.closest('.popup'));}});}}
function popupClose(popupActive){var doUnlock=arguments.length>1&&arguments[1]!==undefined?arguments[1]:true;if(unlock){popupActive.classList.remove('_open');if(doUnlock){bodyUnlock();}}}
function bodyLock(){var lockPaddingValue=window.innerWidth-document.querySelector('.wrapper').offsetWidth+'px';if(lockPadding.length>0){for(var index=0;index<lockPadding.length;index++){var _el=lockPadding[index];_el.style.paddingRight=lockPaddingValue;}}
body.style.paddingRight=lockPaddingValue;body.classList.add('_lock');unlock=false;setTimeout(function(){unlock=true;},timeout);}
function bodyUnlock(){setTimeout(function(){if(lockPadding.length>0){for(var index=0;index<lockPadding.length;index++){var _el2=lockPadding[index];_el2.style.paddingRight='0px';}}
body.style.paddingRight='0px';body.classList.remove('_lock');},timeout);unlock=false;setTimeout(function(){unlock=true;},timeout);}
document.addEventListener('keydown',function(e){if(e.which===27){var popupActive=document.querySelector('.popup._open');popupClose(popupActive);}});(function(){if(!Element.prototype.closest){Element.prototype.closest=function(css){var node=this;while(node){if(node.matches(css))return node;else node=node.parentElement;}
return null;};}})();(function(){if(!Element.prototype.matches){Element.prototype.matches=Element.prototype.matchesSelector||Element.prototype.webkitMatchesSelector||Element.prototype.mozMatchesSelector||Element.prototype.msMatchesSelector;}})();